version: "3.8"

services:
  db:
    image: postgres:15.4
    container_name: db
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./storage/rdb/init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres -d postgres
      interval: 10s
      timeout: 5s
      retries: 20

volumes:
  postgres-data:
