CREATE DATABASE local WITH ENCODING 'UTF8'
  TEMPLATE = template0
  LC_COLLATE = 'C'
  LC_CTYPE = 'C';

CREATE USER api WITH PASSWORD 'api';
GRANT CONNECT ON DATABASE local TO api;
GRANT USAGE ON SCHEMA public TO api;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO api;
